site_name: My
site_url: https://lobanovVA.github.io/test_for_MkDocs/
extra_css:
  - styles/custom.css
extra:
  version:
    provider: mike
    latest: latest
  tags:
    - id: "8.2.0"
      name: "8.2.0"
      description: "February 17, 2022"
      url: /tags/#8.2.0

theme:
  name: material
  features:
    - navigation.tabs      # Включить вкладки для верхнего меню
    - content.tabs.link
    - navigation.sections
    - version-dropdown  # Включает выпадающее меню версий
nav:
  - Home: index.md
  - About:
    - over: a/page2.md
    - under: a/page3.md
    - tags: tags.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - mike
  - tags:
      tags_file: tags.md